# Generated by Django 3.2.9 on 2021-12-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awarrds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='v1638348565/owuk4syvculcljuzdron.jpg', upload_to='images/'),
        ),
    ]
